### ISSUE TITLE
Font Issue

### ISSUE THREAD

**Issue by ec-daisuketanabe** [jhead96/software-eng-bootcamp#1]
Hi

The page came up like this.

![image](https://github.com/jhead96/software-eng-bootcamp/assets/107942885/6ba1bc5b-97be-4483-9afa-751a8fda7699)

Looks like there is an issue with the font file (ttf files).

Can you check the font file to .otf based file?

**Comment by jhead96** [comment]
Hi,

I've replaced custom fonts with just sans-serif now so it should display
properly. It worked fine on Windows + android but apparently Apple doesn't
like ttf.

**Comment by ec-daisuketanabe** [comment]
Thank you. 
I thought it was Mac thing, too.
